name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYWEzNzcyZjQtMjA1MC00NWMxLTk5ZmEtZjVjNzA3Zjg5ZWVmIiwidGVuYW50X2lkIjoiNzZlODA5ZjJjYzE0ODE2NGZkYjVhNzZiZGNhNzA5MTJhOGFlMjdmNWQzNzdmMjJmYjU0MjQ5YWIzNzFjZjZlZCIsImludGVybmFsX3NlY3JldCI6IjVhYzhjNzczLTBkYWItNDhlMS1hMTJhLWFkNmRmZjk2MmM1ZiJ9.bMMVSK6IFapRkZps-ne5TbF-zx4qHcbv2iaZEuOdSNc"

JWT_SECRET="secret"
